### ISSUE TITLE
Take a look at JS implementation

### ISSUE THREAD

**Issue by dabrahams** [val-lang/Lotsawa#7]
I just found a JavaScript implementation, https://github.com/aredridel/lotsawa, which may be of some interest.  

/cc @jeffreykegler

**Comment by jeffreykegler** [comment]
@aredridel and @iarna are supporters of my work from the very early days.  IIRC correctly this implementation didn't reach the point where it was ready for uses.

**Comment by dabrahams** [comment]
Yeah, I don't see them traversing the tree.  However they do some building of prediction bitsets and other things that might have value.  I find it pretty hard to read cweb sources so I can't easily tell whether that was cribbed from MARPA's source.

**Comment by aredridel** [comment]
Indeed, I did not get _that_ far— life intervened and I've not had the deep thought available to come back to it. (And the js ecosystem moved funny; I'd probably use WASM for core parts, the way marpa has some core parts separate from the user interface layer)

**Comment by aredridel** [comment]
But any code in that repo that's useful I am happy to hand off to whoever can use it.

**Comment by dabrahams** [comment]
Not gonna happen, I think.
